name: cameratraps-gui

dependencies:

- python==3.7
- tqdm
- jsonpickle
- Pillow>=5.3.0
- humanfriendly
- matplotlib
- requests
- pandas
- pip

- pip:
  - statistics
  - tensorflow-directml
  - numpy ==1.16.0